-- GENERATED by scripts/seed.js from src/features/plan/data. Do not edit by hand.

insert into public.exercises
  (key, name_en, name_ar, bodyweight_ratio, is_per_hand, timed_seconds, smart_station, alternative_key, is_compound, progression_kg)
values
  ('back_squat', 'Back squat', 'سكوات خلفي بالبار', 1, false, null, 'Rack 3', 'leg_press', true, 5),
  ('leg_press', 'Leg press', 'دفع الأرجل بالجهاز', 1.8, false, null, null, 'back_squat', true, 5),
  ('deadlift', 'Deadlift', 'الرفعة المميتة (ديدلفت)', 1.2, false, null, 'Platform 1', 'romanian_deadlift', true, 5),
  ('romanian_deadlift', 'Romanian deadlift', 'الرفعة الرومانية', 0.85, false, null, null, 'leg_curl', true, 5),
  ('walking_lunge', 'Walking lunges (dumbbells)', 'طعنات المشي بالدمبل', 0.2, true, null, null, 'leg_press', false, 2.5),
  ('leg_curl', 'Leg curl', 'ثني الأرجل بالجهاز', 0.45, false, null, null, 'romanian_deadlift', false, 2.5),
  ('calf_raise', 'Standing calf raise', 'رفع السمانة وقوفًا', 0.9, false, null, null, null, true, 2.5),
  ('bench_press', 'Flat bench press', 'ضغط البنش المستوي', 0.75, false, null, 'Bench 1', 'dumbbell_bench_press', true, 2.5),
  ('dumbbell_bench_press', 'Dumbbell bench press', 'ضغط الدمبل على البنش', 0.3, true, null, null, 'bench_press', false, 2.5),
  ('incline_bench_press', 'Incline bench press', 'ضغط البنش المائل', 0.6, false, null, 'Bench 2', 'incline_dumbbell_press', true, 2.5),
  ('incline_dumbbell_press', 'Incline dumbbell press', 'ضغط الدمبل المائل', 0.25, true, null, null, 'incline_bench_press', false, 2.5),
  ('overhead_press', 'Overhead press', 'ضغط الكتف بالبار', 0.45, false, null, 'Rack 2', 'seated_dumbbell_press', true, 2.5),
  ('seated_dumbbell_press', 'Seated dumbbell press', 'ضغط الكتف بالدمبل جالسًا', 0.2, true, null, null, 'overhead_press', false, 2.5),
  ('barbell_row', 'Barbell row', 'التجديف بالبار', 0.65, false, null, 'Platform 2', 'seated_cable_row', true, 2.5),
  ('seated_cable_row', 'Seated cable row', 'التجديف بالكابل جالسًا', 0.6, false, null, null, 'barbell_row', true, 2.5),
  ('lat_pulldown', 'Lat pulldown', 'السحب الأمامي بالكابل', 0.6, false, null, null, 'seated_cable_row', true, 2.5),
  ('lateral_raise', 'Lateral raise', 'الرفرفة الجانبية', 0.08, true, null, null, null, false, 2.5),
  ('dumbbell_curl', 'Dumbbell curl', 'ثني الذراع بالدمبل', 0.12, true, null, null, null, false, 2.5),
  ('triceps_pushdown', 'Triceps pushdown', 'دفع الترايسبس بالكابل', 0.3, false, null, null, null, false, 2.5),
  ('plank', 'Plank', 'البلانك', 0, false, 45, null, null, false, 2.5)
on conflict (key) do update set
  name_en = excluded.name_en,
  name_ar = excluded.name_ar,
  bodyweight_ratio = excluded.bodyweight_ratio,
  is_per_hand = excluded.is_per_hand,
  timed_seconds = excluded.timed_seconds,
  smart_station = excluded.smart_station,
  alternative_key = excluded.alternative_key,
  is_compound = excluded.is_compound,
  progression_kg = excluded.progression_kg;

insert into public.workout_templates (key, name_en, name_ar, exercise_keys)
values
  ('full_body_a', 'Full body A', 'الجسم كامل (أ)', array['back_squat', 'bench_press', 'barbell_row', 'lateral_raise', 'plank']::text[]),
  ('full_body_b', 'Full body B', 'الجسم كامل (ب)', array['deadlift', 'overhead_press', 'lat_pulldown', 'incline_dumbbell_press', 'dumbbell_curl']::text[]),
  ('full_body_c', 'Full body C', 'الجسم كامل (ج)', array['leg_press', 'incline_bench_press', 'seated_cable_row', 'romanian_deadlift', 'triceps_pushdown']::text[]),
  ('upper_a', 'Upper body A', 'الجزء العلوي (أ)', array['bench_press', 'barbell_row', 'overhead_press', 'lat_pulldown', 'lateral_raise', 'triceps_pushdown']::text[]),
  ('lower_a', 'Lower body A', 'الجزء السفلي (أ)', array['back_squat', 'romanian_deadlift', 'walking_lunge', 'leg_curl', 'calf_raise', 'plank']::text[]),
  ('upper_b', 'Upper body B', 'الجزء العلوي (ب)', array['incline_bench_press', 'lat_pulldown', 'seated_dumbbell_press', 'seated_cable_row', 'dumbbell_curl', 'triceps_pushdown']::text[]),
  ('lower_b', 'Lower body B', 'الجزء السفلي (ب)', array['deadlift', 'walking_lunge', 'leg_press', 'leg_curl', 'calf_raise']::text[]),
  ('push', 'Push', 'تمارين الدفع', array['bench_press', 'overhead_press', 'incline_dumbbell_press', 'lateral_raise', 'triceps_pushdown']::text[]),
  ('pull', 'Pull', 'تمارين السحب', array['barbell_row', 'lat_pulldown', 'seated_cable_row', 'dumbbell_curl']::text[]),
  ('legs', 'Legs', 'تمارين الأرجل', array['back_squat', 'romanian_deadlift', 'leg_press', 'leg_curl', 'calf_raise']::text[])
on conflict (key) do update set
  name_en = excluded.name_en,
  name_ar = excluded.name_ar,
  exercise_keys = excluded.exercise_keys;

insert into public.meal_templates (key, day_type, slot, ramadan_slot, share, name_en, name_ar, sort_order)
values
  ('high_breakfast', 'high'::public.day_type, 'breakfast', 'suhoor', 0.25, 'Oats with banana, honey and a scoop of whey', 'شوفان مع موز وعسل ومغرفة بروتين', 0),
  ('high_lunch', 'high'::public.day_type, 'lunch', 'iftar', 0.3, 'Grilled chicken, rice and salad', 'دجاج مشوي مع أرز وسلطة', 1),
  ('high_pre_workout', 'high'::public.day_type, 'pre_workout', 'pre_workout', 0.15, 'Dates and Greek yogurt', 'تمر مع زبادي يوناني', 2),
  ('high_dinner', 'high'::public.day_type, 'dinner', 'recovery', 0.3, 'Lean beef, potatoes and vegetables', 'لحم بقري قليل الدهن مع بطاطس وخضار', 3),
  ('medium_breakfast', 'medium'::public.day_type, 'breakfast', 'suhoor', 0.25, 'Foul medames, 3 eggs and wholegrain bread', 'فول مدمس مع 3 بيضات وخبز أسمر', 4),
  ('medium_lunch', 'medium'::public.day_type, 'lunch', 'iftar', 0.3, 'Chicken shawarma plate, half rice, salad', 'صحن شاورما دجاج مع نصف حصة أرز وسلطة', 5),
  ('medium_snack', 'medium'::public.day_type, 'snack', 'snack', 0.15, 'Greek yogurt with berries', 'زبادي يوناني مع توت', 6),
  ('medium_dinner', 'medium'::public.day_type, 'dinner', 'recovery', 0.3, 'Salmon, sweet potato and greens', 'سلمون مع بطاطا حلوة وخضار ورقية', 7),
  ('low_breakfast', 'low'::public.day_type, 'breakfast', 'suhoor', 0.25, 'Omelette with cheese, cucumber and olives', 'أومليت بالجبن مع خيار وزيتون', 8),
  ('low_lunch', 'low'::public.day_type, 'lunch', 'iftar', 0.3, 'Grilled fish, big salad with tahini', 'سمك مشوي مع سلطة كبيرة بالطحينة', 9),
  ('low_snack', 'low'::public.day_type, 'snack', 'snack', 0.15, 'Protein shake and a handful of nuts', 'مخفوق بروتين وحفنة من المكسرات', 10),
  ('low_dinner', 'low'::public.day_type, 'dinner', 'recovery', 0.3, 'Chicken or beef with vegetables and avocado', 'دجاج أو لحم مع خضار وأفوكادو', 11)
on conflict (key) do update set
  day_type = excluded.day_type,
  slot = excluded.slot,
  ramadan_slot = excluded.ramadan_slot,
  share = excluded.share,
  name_en = excluded.name_en,
  name_ar = excluded.name_ar,
  sort_order = excluded.sort_order;
