-- GENERATED by scripts/seed.js from src/features/plan/data. Do not edit by hand.

insert into public.exercises
  (key, name_en, name_ar, bodyweight_ratio, is_per_hand, timed_seconds, smart_station, alternative_key, is_compound)
values
  ('back_squat', 'Back squat', 'سكوات خلفي بالبار', 1, false, null, 'Rack 3', 'leg_press', true),
  ('leg_press', 'Leg press', 'دفع الأرجل بالجهاز', 1.8, false, null, null, 'back_squat', true),
  ('deadlift', 'Deadlift', 'الرفعة المميتة (ديدلفت)', 1.2, false, null, 'Platform 1', 'romanian_deadlift', true),
  ('romanian_deadlift', 'Romanian deadlift', 'الرفعة الرومانية', 0.85, false, null, null, 'leg_curl', true),
  ('walking_lunge', 'Walking lunges (dumbbells)', 'طعنات المشي بالدمبل', 0.2, true, null, null, 'leg_press', false),
  ('leg_curl', 'Leg curl', 'ثني الأرجل بالجهاز', 0.45, false, null, null, 'romanian_deadlift', false),
  ('calf_raise', 'Standing calf raise', 'رفع السمانة وقوفًا', 0.9, false, null, null, null, true),
  ('bench_press', 'Flat bench press', 'ضغط البنش المستوي', 0.75, false, null, 'Bench 1', 'dumbbell_bench_press', true),
  ('dumbbell_bench_press', 'Dumbbell bench press', 'ضغط الدمبل على البنش', 0.3, true, null, null, 'bench_press', false),
  ('incline_bench_press', 'Incline bench press', 'ضغط البنش المائل', 0.6, false, null, 'Bench 2', 'incline_dumbbell_press', true),
  ('incline_dumbbell_press', 'Incline dumbbell press', 'ضغط الدمبل المائل', 0.25, true, null, null, 'incline_bench_press', false),
  ('overhead_press', 'Overhead press', 'ضغط الكتف بالبار', 0.45, false, null, 'Rack 2', 'seated_dumbbell_press', true),
  ('seated_dumbbell_press', 'Seated dumbbell press', 'ضغط الكتف بالدمبل جالسًا', 0.2, true, null, null, 'overhead_press', false),
  ('barbell_row', 'Barbell row', 'التجديف بالبار', 0.65, false, null, 'Platform 2', 'seated_cable_row', true),
  ('seated_cable_row', 'Seated cable row', 'التجديف بالكابل جالسًا', 0.6, false, null, null, 'barbell_row', true),
  ('lat_pulldown', 'Lat pulldown', 'السحب الأمامي بالكابل', 0.6, false, null, null, 'seated_cable_row', true),
  ('lateral_raise', 'Lateral raise', 'الرفرفة الجانبية', 0.08, true, null, null, null, false),
  ('dumbbell_curl', 'Dumbbell curl', 'ثني الذراع بالدمبل', 0.12, true, null, null, null, false),
  ('triceps_pushdown', 'Triceps pushdown', 'دفع الترايسبس بالكابل', 0.3, false, null, null, null, false),
  ('plank', 'Plank', 'البلانك', 0, false, 45, null, null, false)
on conflict (key) do update set
  name_en = excluded.name_en,
  name_ar = excluded.name_ar,
  bodyweight_ratio = excluded.bodyweight_ratio,
  is_per_hand = excluded.is_per_hand,
  timed_seconds = excluded.timed_seconds,
  smart_station = excluded.smart_station,
  alternative_key = excluded.alternative_key,
  is_compound = excluded.is_compound;

insert into public.workout_templates (key, name_en, name_ar, exercise_keys)
values
  ('full_body_a', 'Full body A', 'الجسم كامل (أ)', array['back_squat', 'bench_press', 'barbell_row', 'lateral_raise', 'plank']::text[]),
  ('full_body_b', 'Full body B', 'الجسم كامل (ب)', array['deadlift', 'overhead_press', 'lat_pulldown', 'incline_dumbbell_press', 'dumbbell_curl']::text[]),
  ('full_body_c', 'Full body C', 'الجسم كامل (ج)', array['leg_press', 'incline_bench_press', 'seated_cable_row', 'romanian_deadlift', 'triceps_pushdown']::text[]),
  ('upper_a', 'Upper body A', 'الجزء العلوي (أ)', array['bench_press', 'barbell_row', 'overhead_press', 'lat_pulldown', 'lateral_raise', 'triceps_pushdown']::text[]),
  ('lower_a', 'Lower body A', 'الجزء السفلي (أ)', array['back_squat', 'romanian_deadlift', 'walking_lunge', 'leg_curl', 'calf_raise', 'plank']::text[]),
  ('upper_b', 'Upper body B', 'الجزء العلوي (ب)', array['incline_bench_press', 'lat_pulldown', 'seated_dumbbell_press', 'seated_cable_row', 'dumbbell_curl', 'triceps_pushdown']::text[]),
  ('lower_b', 'Lower body B', 'الجزء السفلي (ب)', array['deadlift', 'walking_lunge', 'leg_press', 'leg_curl', 'calf_raise']::text[]),
  ('push', 'Push', 'تمارين الدفع', array['bench_press', 'overhead_press', 'incline_dumbbell_press', 'lateral_raise', 'triceps_pushdown']::text[]),
  ('pull', 'Pull', 'تمارين السحب', array['barbell_row', 'lat_pulldown', 'seated_cable_row', 'dumbbell_curl']::text[]),
  ('legs', 'Legs', 'تمارين الأرجل', array['back_squat', 'romanian_deadlift', 'leg_press', 'leg_curl', 'calf_raise']::text[])
on conflict (key) do update set
  name_en = excluded.name_en,
  name_ar = excluded.name_ar,
  exercise_keys = excluded.exercise_keys;
