// Generates supabase/seed.sql from the plan engine's content data, so the app's JSON and the
// database content tables never drift apart. Run with: npm run db:seed:generate
// A Jest test fails if the committed seed.sql is out of date.

const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const dataDir = path.join(root, 'src/features/plan/data');
const seedPath = path.join(root, 'supabase/seed.sql');

const read = (file) => JSON.parse(fs.readFileSync(path.join(dataDir, file), 'utf8'));
const lit = (v) =>
  v === undefined || v === null
    ? 'null'
    : typeof v === 'number' || typeof v === 'boolean'
      ? String(v)
      : `'${String(v).replace(/'/g, "''")}'`;
const arr = (values) => `array[${values.map(lit).join(', ')}]::text[]`;

function generateSeed() {
  const exercises = read('exercises.json');
  const workouts = read('workouts.json');

  const exerciseRows = exercises.map((e) =>
    [
      lit(e.key),
      lit(e.nameEn),
      lit(e.nameAr),
      lit(e.bodyweightRatio),
      lit(!!e.perHand),
      lit(e.timedSeconds),
      lit(e.smartStation),
      lit(e.alternativeKey),
      lit(!!e.isMain),
    ].join(', '),
  );
  const workoutRows = workouts.map((w) =>
    [lit(w.key), lit(w.nameEn), lit(w.nameAr), arr(w.exerciseKeys)].join(', '),
  );

  return `-- GENERATED by scripts/seed.js from src/features/plan/data. Do not edit by hand.

insert into public.exercises
  (key, name_en, name_ar, bodyweight_ratio, is_per_hand, timed_seconds, smart_station, alternative_key, is_compound)
values
${exerciseRows.map((r) => `  (${r})`).join(',\n')}
on conflict (key) do update set
  name_en = excluded.name_en,
  name_ar = excluded.name_ar,
  bodyweight_ratio = excluded.bodyweight_ratio,
  is_per_hand = excluded.is_per_hand,
  timed_seconds = excluded.timed_seconds,
  smart_station = excluded.smart_station,
  alternative_key = excluded.alternative_key,
  is_compound = excluded.is_compound;

insert into public.workout_templates (key, name_en, name_ar, exercise_keys)
values
${workoutRows.map((r) => `  (${r})`).join(',\n')}
on conflict (key) do update set
  name_en = excluded.name_en,
  name_ar = excluded.name_ar,
  exercise_keys = excluded.exercise_keys;
`;
}

module.exports = { generateSeed, seedPath };

if (require.main === module) {
  fs.writeFileSync(seedPath, generateSeed());
  console.log(`Wrote ${path.relative(root, seedPath)}`);
}
